name: build and push docker image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: build proto contracts
        run: ./gradlew proto-compiler:build

      - name: build and push jvm-mode docker image
        run: ./gradlew server:jib
      - name: build and push jvm-mode latest version docker image
        run: docker tag hegemonies/kmq:0.0.1 hegemonies/kmq:latest && docker push hegemonies/kmq:latest
